// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { checkRateLimit, RATE_LIMIT_CONFIG } from '@/lib/rate-limiter'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      console.error(`[Supabase] Missing env var(s): ${missing.join(', ')}`);
      throw new Error('Service temporarily unavailable');
    }

    const request = getRequest();
    const ip = request?.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || request?.headers.get("x-real-ip") || "unknown";
    
    const { allowed } = checkRateLimit(`public:${ip}`, {
      windowSeconds: RATE_LIMIT_CONFIG.public.perIp.windowSeconds,
      maxRequests: RATE_LIMIT_CONFIG.public.perIp.maxRequests,
    });
    
    if (!allowed) {
      console.error(`[Auth] Rate limit exceeded for IP: ${ip}`);
      throw new Error('Too many requests. Please try again later.');
    }
    

    if (!request?.headers) {
      console.error('[Auth] No request headers available');
      throw new Error('Authentication required');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Authentication required');
    }

    if (!authHeader.startsWith('Bearer ')) {
      console.error('[Auth] Non-bearer auth header received');
      throw new Error('Authentication required');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Authentication required');
    }

    if (token.split('.').length !== 3) {
      console.error('[Auth] Malformed token (not 3-part JWT)');
      throw new Error('Authentication required');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      console.error('[Auth] Token validation failed:', error?.message ?? 'no claims');
      throw new Error('Authentication required');
    }

    if (!data.claims.sub) {
      console.error('[Auth] Token has no sub claim');
      throw new Error('Authentication required');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
